kind: pipeline
type: kubernetes
name: webbase
steps:
  - name: test-node-12
    image: node:12
    commands:
      - yarn
      - yarn lint
      - yarn build

  - name: test-node-14
    image: node:14
    commands:
      - yarn
      - yarn lint
      - yarn build

  - name: docker-registry
    image: plugins/docker
    settings:
      repo: minskylab/webbase
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        - master

  - name: telegram-notification
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: telegram_token
      to:
        from_secret: telegram_to_id
    when:
      status:
        - failure
        - success
    depends_on:
      - docker-registry
